apiVersion: v1
entries:
  busybox:
  - apiVersion: v2
    created: "2022-06-20T13:15:12.457017-10:00"
    description: A utility chart to verify clusters and processes
    digest: 22bf6560781a75d99052c78537263995fac4a1ab658e5ebbce15f1b8b9c054c4
    home: https://www.busybox.net/
    icon: https://www.busybox.net/images/busybox1.png
    keywords:
    - busybox
    - testing
    - sanity check
    - network
    - connectivity
    name: busybox
    type: application
    urls:
    - https://ronballesteros.github.io/helm-chart/charts/busybox-0.1.0.tgz
    version: 0.1.0
generated: "2022-06-20T13:15:12.456315-10:00"
